[profile.default]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib", "node_modules"]
remappings = ["@rmrk-team/=node_modules/@rmrk-team/"]

# Etherscan verification disabled for local development
